
    <div id="core_a"><p><span class="anchor_label">(a) </span><span class="sense">The mother tells her sons of their sister’s abduction at
        the hands of the Emir, and commands:</span><span class="anchor_label"> [G1.65-74]</span></p></div>
    <div id="core_b"><p><span class="anchor_label">(b) </span><span class="lines">Lay down your lives rather than fail to recover your
        sister.</span><span class="anchor_label"> [G1.75-76]</span></p></div>
    <div id="core_c"><p><span class="anchor_label">(c) </span><span class="sense">The mother threatens with a curse; the brothers agree to
        recover their sister.</span><span class="anchor_label"> [G1.78-85]</span></p></div>
    <div id="core_d"><p><span class="anchor_label">(d) </span><span class="lines">They mounted their horses and set off.</span><span class="anchor_label"> [G1.86]</span></p></div>
    <div id="core_e"><p><span class="anchor_label">(e) </span><span class="sense">The brothers reach the border of the Saracen land,</span><span class="anchor_label"> [G1.88-89]</span></p></div>
    <div id="core_f"><p><span class="anchor_label">(f) </span><span class="lines">a pass/river named Difficult/Purple; there they met a
        sentry/ies,</span><span class="anchor_label"> [G1.90-91]</span></p></div>
    <div id="core_g"><p><span class="anchor_label">(g) </span><span class="sense">and are led to/told of the Emir.</span><span class="anchor_label"> [G1.92-93]</span></p></div>
    <div id="core_h"><p><span class="anchor_label">(h) </span><span class="lines">The Emir’s throne/tent is decorated with gold, and
        surrounded by soldiers.</span><span class="anchor_label"> [G1.94-96]</span></p></div>
    <div id="core_i"><p><span class="anchor_label">(i) </span><span class="sense">The brothers communicate their message to the Emir. He
        tells them:</span><span class="anchor_label"> [G1.99-116]</span></p></div>
    <div id="core_j"><p><span class="anchor_label">(j) </span><span class="lines">If I defeat you, I will enslave/kill you; if
        you defeat me, take your sister. The brothers cast lots to fight the Emir: it fell to the
        youngest, the girl’s twin. They tell him:</span><span class="anchor_label"> [G1.121-123, 129-132]</span></p></div>
    <div id="core_1"><p><span class="anchor_label">(1) </span><span class="lines">Brother, don’t be frightened; think of your
        mother’s curse.</span><span class="anchor_label"> [E1-2; G1.134-135, 138]</span></p></div>
    <div id="core_2"><p><span class="anchor_label">(2) </span><span class="sense">The brothers call on God; arming of combatant(s)
        follows. The Emir rides out to battle, his appearance connected to the sun’s rays.</span><span class="anchor_label"> [E8-16; G1.140-163]</span></p></div>
    <div id="core_3"><p><span class="anchor_label">(3) </span><span class="lines">He wielded a blue gilded spear.</span><span class="anchor_label"> [E17; G1.164]</span></p></div>
    <div id="core_4"><p><span class="anchor_label">(4) </span><span class="sense">A retainer warns the Emir not to underestimate his
        opponent:</span><span class="anchor_label"> [E21-27; G1.155-160]</span></p></div>
    <div id="core_5"><p><span class="anchor_label">(5) </span><span class="lines">Don’t let him harm you! Entry
        of the opponent(s) and description of nature.</span><span class="anchor_label"> [E29, 32, 38, 40; G1.189, 172, 180, 181]</span></p></div>
    <div id="core_6"><p><span class="anchor_label">(6) </span><span class="sense">The retainers again give advice, and the Emir
        concedes defeat:</span><span class="anchor_label"> [E46-51; G1.184-189]</span></p></div>
    <div id="core_7"><p><span class="anchor_label">(7) </span><span class="lines">Young man, victory is yours.</span><span class="anchor_label"> [E55; G196]</span></p></div>
    <div id="core_8"><p><span class="anchor_label">(8) </span><span class="sense">The battle over, the brothers together address the
        Emir.</span><span class="anchor_label"> [E56-57; G1.198-204]</span></p></div>
    <div id="core_9"><p><span class="anchor_label">(9) </span><span class="lines">Give us our sister, as you promised. The Emir
        replied: Go search the tents of the army.</span><span class="anchor_label"> [E59-63; G1.206, 208-209]</span></p></div>
    <div id="core_10"><p><span class="anchor_label">(10) </span><span class="sense">If you find her, take her and go. As they go to the
        tents,</span><span class="anchor_label"> [E64; G1.210-211]</span></p></div>
    <div id="core_11"><p><span class="anchor_label">(11) </span><span class="lines">they met a Saracen.</span><span class="anchor_label"> [E67; G1.216]</span></p></div>
    <div id="core_12"><p><span class="anchor_label">(12) </span><span class="sense">Asked about the captured girl, he tells them:</span><span class="anchor_label"> [E68-70; G1.217-222]</span></p></div>
    <div id="core_13"><p><span class="anchor_label">(13) </span><span class="lines">Go to the high/low ground: there you’ll find a
        ditch where we killed some girls who wouldn’t do what we wanted.</span><span class="anchor_label"> [E71-73; G1.223-225]</span></p></div>
    <div id="core_14"><p><span class="anchor_label">(14) </span><span class="sense">The brothers follow these directions.</span><span class="anchor_label"> [E74-78; G1.226]</span></p></div>
    <div id="core_15"><p><span class="anchor_label">(15) </span><span class="lines">They found slaughtered girls, without limbs and
        heads.</span><span class="anchor_label"> [E79-80; G1.227-228]</span></p></div>
    <div id="core_16"><p><span class="anchor_label">(16) </span><span class="sense">They try to find their sister without success.</span><span class="anchor_label"> [E82-85; G1.230]</span></p></div>
    <div id="core_17"><p><span class="anchor_label">(17) </span><span class="lines">[repetition of E79=G1.227 at E87 only]</span><span class="anchor_label"> [E87; G1.227]</span></p></div>
    <div id="core_18"><p><span class="anchor_label">(18) </span><span class="sense">They put earth on their heads and lament:</span><span class="anchor_label"> [E88-86; G1.231-252]</span></p></div>
    <div id="core_19"><p><span class="anchor_label">(19) </span><span class="lines">Lord Sun, why have you done this?</span><span class="anchor_label"> [E91, 94; G1.253-254]</span></p></div>
    <div id="core_20"><p><span class="anchor_label">(20) </span><span class="sense">They bury the girls in a common grave.</span><span class="anchor_label"> [E123-125; G1.255-258]</span></p></div>
    <div id="core_21"><p><span class="anchor_label">(21) </span><span class="lines">Lamenting, they returned to the Emir.</span><span class="anchor_label"> [E126; G1.257]</span></p></div>
    <div id="core_22"><p><span class="anchor_label">(22) </span><span class="lines">[repetition of E59=G1.100 at E129 only]</span><span class="anchor_label"> [E129; G1.100]</span></p></div>
    <div id="core_23"><p><span class="anchor_label">(23) </span><span class="sense">The brothers threaten violence unless their sister is returned.
        The Emir inquires about their lineage and they recount it. The Emir replies:</span></p></div>
    <div id="core_24"><p><span class="anchor_label">(24) </span><span class="lines">I descend from Aa(mb)ron and Karoi(li)s; no
        general can withstand me.</span><span class="anchor_label"> [E145, 149; G1.285, 297]</span></p></div>
    <div id="core_25"><p><span class="anchor_label">(25) </span><span class="sense">But now I am defeated by a girl’s beauty; and so:</span><span class="anchor_label"> [G1.298]</span></p></div>
    <div id="core_26"><p><span class="anchor_label">(26) </span><span class="lines">Accept me as your
        brother-in-law. I swear that I have not touched your sister. Come to my tent and find her. I
        will go with you and convert.</span><span class="anchor_label"> [E162-164, 166, 177; G1.304, 306-309]</span></p></div>
    <div id="core_27"><p><span class="anchor_label">(27) </span><span class="sense">The brothers go and find their sister in a luxurious
        tent,  on a coverlet of/couch draped in gold. They say:</span><span class="anchor_label"> [E180; G1.312]</span></p></div>
    <div id="core_28"><p><span class="anchor_label">(28) </span><span class="lines">We thought you were dead!</span><span class="anchor_label"> [E189; G1.323]</span></p></div>
    <div id="core_29"><p><span class="anchor_label">(29) </span><span class="sense">The brothers embrace their sister.</span></p></div>
    <div id="core_30"><p><span class="anchor_label">(30) </span><span class="lines">[repetition of kissing formula: cf. G4.190-191]</span><span class="anchor_label"> [E195; G1.204]</span></p></div>
    <div id="core_31"><p><span class="anchor_label">(31) </span><span class="sense">They all returned rejoicing to the Roman land.</span></p></div>
    <div id="core_32"><p><span class="anchor_label">(32) </span><span class="lines">And it became renowned throughout the world,</span><span class="anchor_label"> [E213; G1.335]</span></p></div>
    <div id="core_33"><p><span class="anchor_label">(33) </span><span class="sense">that beauty could defeat a whole army. After the marriage is
        consummated,</span></p></div>
    <div id="core_34"><p><span class="anchor_label">(34) </span><span class="lines">they bore Digenis Akritis (Twyborn the Borderer).</span><span class="anchor_label"> [E219; G2.48]</span></p></div>
    <div id="core_35"><p><span class="anchor_label">(35) </span><span class="lines">The Emir’s mother sent him a letter from Syria,
        full of lament and reproach: Beloved child,</span><span class="anchor_label"> [E226-228; G2.50-53]</span></p></div>
    <div id="core_36"><p><span class="anchor_label">(36) </span><span class="sense">You’ve shamed your family; don’t you remember the deeds of your
        (grand)father?</span></p></div>
    <div id="core_37"><p><span class="anchor_label">(37) </span><span class="lines">How many Romans he killed and
        enslaved? And your uncle?</span><span class="anchor_label"> [E255-256, 258, 261; G2.61-62, 75]</span></p></div>
    <div id="core_38"><p><span class="anchor_label">(38) </span><span class="sense">And now you’ve thrown all this away for a pork-eater! If you
        want my blessing,</span></p></div>
    <div id="core_39"><p><span class="anchor_label">(39) </span><span class="lines">I have sent you choice horses: mount the
        chestnut, (lead the black, let the bay follow) and no one will catch you.</span><span class="anchor_label"> [E275, 279-281; G2.94-96]</span></p></div>
    <div id="core_40"><p><span class="anchor_label">(40) </span><span class="sense">Bring the Roman girl if you like. Otherwise,</span><span class="anchor_label"> [E282-283; G2.97]</span></p></div>
    <div id="core_41"><p><span class="anchor_label">(41) </span><span class="lines">they will kill your children,</span><span class="anchor_label"> [E286; G2.86]</span></p></div>
    <div id="core_42"><p><span class="anchor_label">(42) </span><span class="sense">and your wives will be embraced by others. And I
        will curse you.</span><span class="anchor_label"> [E287-291; G2.87-98]</span></p></div>
    <div id="core_43"><p><span class="anchor_label">(43) </span><span class="sense">Messengers bring his mother’s letter and camp near the
        Emir’s estate. They urge him to leave with them. But he goes to the girl and tells her:</span><span class="anchor_label"> [E292; G2.100]</span></p></div>
    <div id="core_44"><p><span class="anchor_label">(44) </span><span class="lines">My mother has sent me a letter from Syria.</span><span class="anchor_label"> [E307; G2.127]</span></p></div>
    <div id="core_45"><p><span class="anchor_label">(45) </span><span class="lines">The girl’s youngest brother had a dream.</span><span class="anchor_label"> [E318; G2.136]</span></p></div>
    <div id="core_46"><p><span class="anchor_label">(46) </span><span class="sense">He tells his brother his dream of a gold-winged
        falcon pursuing a dove.</span><span class="anchor_label"> [E320-325; G135-146]</span></p></div>
    <div id="core_47"><p><span class="anchor_label">(47) </span><span class="lines">The brother interpreted: Hawks stand for
        abductors,</span><span class="anchor_label"> [E326-327; G2.147-148]</span></p></div>
    <div id="core_48"><p><span class="anchor_label">(48) </span><span class="sense">the falcon is our brother-in-law, and the dove is our sister.
        They go to the camp and confront the messengers:</span></p></div>
    <div id="core_49"><p><span class="anchor_label">(49) </span><span class="lines">Welcome, our brother-in-law’s youngsters!</span><span class="anchor_label"> [E335; G2.156]</span></p></div>
    <div id="core_50"><p><span class="anchor_label">(50) </span><span class="sense">Why camp here and not come to the house? They go to the Emir
        and threaten him:</span></p></div>
    <div id="core_51"><p><span class="anchor_label">(51) </span><span class="lines">Leave our sister, renounce your son.</span><span class="anchor_label"> [E346; G2.168]</span></p></div>
    <div id="core_52"><p><span class="anchor_label">(52) </span><span class="sense">Take your property and go back to Syria. The Emir is upset and
        reproaches his wife:</span></p></div>
    <div id="core_53"><p><span class="anchor_label">(53) </span><span class="lines">Don’t you remember how it was at the beginning?</span><span class="anchor_label"> [E355; G2.187]</span></p></div>
    <div id="core_54"><p><span class="anchor_label">(54) </span><span class="sense">I took you as a slave,</span></p></div>
    <div id="core_55"><p><span class="anchor_label">(55) </span><span class="lines">and now I am your slave.</span><span class="anchor_label"> [E357; G2.189]</span></p></div>
    <div id="core_56"><p><span class="anchor_label">(56) </span><span class="sense">Now your brothers intend to kill me.</span></p></div>
    <div id="core_57"><p><span class="anchor_label">(57) </span><span class="lines">I shall draw my sword and kill myself,</span><span class="anchor_label"> [E367; G2.196]</span></p></div>
    <div id="core_58"><p><span class="anchor_label">(58) </span><span class="sense">and the Roman nobles will reproach you.</span></p></div>
    <div id="core_59"><p><span class="anchor_label">(59) </span><span class="sense">The girl protests her innocence and goes to her brothers: Why
        do you attack the Emir, who is innocent?</span></p></div>
    <div id="core_60"><p><span class="anchor_label">(60) </span><span class="lines">He is delerious from grief!</span><span class="anchor_label"> [E395; G2.218]</span></p></div>
    <div id="core_61"><p><span class="anchor_label">(61) </span><span class="sense">He gave up his faith and family for me,</span></p></div>
    <div id="core_62"><p><span class="anchor_label">(62) </span><span class="lines">and came to Roman territory for my sake.
        He fears his mother’s curse just like you did.</span><span class="anchor_label"> [E399, 404, 406; G2.228, 231]</span></p></div>
    <div id="core_63"><p><span class="anchor_label">(63) </span><span class="sense">The brothers are moved. You are our life and soul, they say; if
        the Emir wants to go,</span></p></div>
    <div id="core_64"><p><span class="anchor_label">(64) </span><span class="lines">to see his mother and return,</span><span class="anchor_label"> [E411; G2.184]</span></p></div>
    <div id="core_65"><p><span class="anchor_label">(65) </span><span class="sense">he has our blessing. They go to the Emir and ask forgiveness.
        He swears to be faithful, and readies for his trip. Before leaving he goes to the girl.</span></p></div>
    <div id="core_66"><p><span class="anchor_label">(66) </span><span class="lines">His tears fell like showers,</span><span class="anchor_label"> [E468; G2.267]</span></p></div>
    <div id="core_67"><p><span class="anchor_label">(67) </span><span class="sense">and he asks for her ring. She gives it to him as a reminder of
        their vows. He mounts his horse, and his in-laws see him off.</span></p></div>
    <div id="core_68"><p><span class="anchor_label">(68) </span><span class="sense">Starting out, the Emir makes a speech to his retainers:</span></p></div>
    <div id="core_69"><p><span class="anchor_label">(69) </span><span class="lines">Youngsters, be strong, and struggle against
        the elements,</span><span class="anchor_label"> [E487, 490; G3.22, 3.24]</span></p></div>
    <div id="core_70"><p><span class="anchor_label">(70) </span><span class="sense">so that I may return quickly. And they set out.</span><span class="anchor_label"> [E494; G3.47]</span></p></div>
    <div id="core_71"><p><span class="anchor_label">(71) </span><span class="sense">The Emir recounts his exploits to his retainers. He kills a
        lion and asks them to send its (hide,) teeth and claws to his son.</span></p></div>
    <div id="core_72"><p><span class="anchor_label">(72) </span><span class="lines">And when they had made their way to Raqqa(b),</span><span class="anchor_label"> [E327; G3.111]</span></p></div>
    <div id="core_73"><p><span class="anchor_label">(73) </span><span class="sense">they camp outside and are greeted by the Emir’s mother:</span></p></div>
    <div id="core_74"><p><span class="anchor_label">(74) </span><span class="lines">My sweetest child, light of my eyes!</span><span class="anchor_label"> [E539-540; G3.132]</span></p></div>
    <div id="core_75"><p><span class="anchor_label">(75) </span><span class="sense">The Emir persuades his mother and her
        retainers to return with him and convert. On his return he embraces his wife and baptizes
        those who have come with him.</span><span class="anchor_label"> [E583, 608; G3.279-281, 329-333]</span></p></div>
