
   <p>
   <cite>
      </cite>
   <span class="page">[Tit 183v] </span>
   <cite>Of the Marriage of Devgenij and the Abduction of Stratigovna</cite>
</p>
   <div id="a1">
      <p>
      <span class="anchor_label">(1) </span>
      <span class="page">[Tit 183v] </span>Glorious Devgenij began <span class="page">[184r] </span> ever to think about
         Stratigovna, how he might see Stratig and his children and all his soldiers and the fair
         Stratigovna.</p>
   </div>
   <div id="a2">
      <p>
      <span class="anchor_label">(2) </span>
      <span class="page">[184r] </span>His father and mother began to restrain him: "Child, give up this
         thought.</p>
   </div>
   <div id="a3">
      <p>
      <span class="anchor_label">(3) </span>
      <span class="page">[184r] </span>Many have thought about Stratig himself and about Stratigovna, how they
         might see her, but it has availed them not."</p>
   </div>
   <div id="a4">
      <p>
      <span class="anchor_label">(4) </span>
      <span class="page">[184r] </span>Glorious Devgenij took a prayer from his father and from his mother and
         assembled a few soldiers</p>
   </div>
   <div id="a5">
      <p>
      <span class="anchor_label">(5) </span>
      <span class="page">[184r] </span>and took with him costly vestments and a musical
         zither</p>
   </div>
   <div id="a6">
      <p>
      <span class="anchor_label">(6) </span>
      <span class="page">[184r] </span>and mounted a horse, his swift Far', and went to Stratig.</p>
   </div>
   <div id="a7">
      <p>
      <span class="anchor_label">(7) </span>
      <span class="page">[184r] </span>And he reached the border of Stratig's land and went within five leagues of
         the city</p>
   </div>
   <div id="a8">
      <p>
      <span class="anchor_label">(8) </span>
      <span class="page">[184r] </span>and disposed his army and ordered them to mount guard among themselves and
         to be strong, while he himself went to Stratig's city.</p>
   </div>
   <div id="a9">
      <p>
      <span class="anchor_label">(9) </span>
      <span class="page">[184r] </span>And he entered the city through the gates of the city of Stratig</p>
   </div>
   <div id="a10">
      <p>
      <span class="anchor_label">(10) </span>
      <span class="page">[184r] </span>and met a youth of Stratig's court and questioned him about Stratig and
         about his sons and about Stratigovna herself.</p>
   </div>
   <div id="a11">
      <p>
      <span class="anchor_label">(11) </span>
      <span class="page">[184r] </span>The youth replied to him: "Our lord Stratig is not at home, but hunting in
         another country with his four sons.</p>
   </div>
   <div id="a12">
      <p>
      <span class="anchor_label">(12) </span>
      <span class="page">[184r] </span>And you ask about Stratigovna: to our lord there is not another so fair in
         the world. Many have <span class="page">[184v] </span> come, but no one has looked in her eyes,</p>
   </div>
   <div id="a13">
      <p>
      <span class="anchor_label">(13) </span>
      <span class="page">[184v] </span>since Stratig is brave and strong, and his sons, and the rest of his army;
         one will attack a hundred.</p>
   </div>
   <div id="a14">
      <p>
      <span class="anchor_label">(14) </span>
      <span class="page">[184v] </span>Stratigovna herself has manly boldness;</p>
   </div>
   <div id="a15">
      <p>
      <span class="anchor_label">(15) </span>
      <span class="page">[184v] </span>to no one else is she like save to you."</p>
   </div>
   <div id="a16">
      <p>
      <span class="anchor_label">(16) </span>
      <span class="page">[184v] </span>When Devgenij heard, he was joyful, since it had been shown to him and
         written: He who joins with Stratigovna will live for thirty-six years.
      </p>
   </div>
   <div id="a21">
      <p>
      <span class="anchor_label">(21) </span>
      <span class="page">[10r] </span>When she heard this, the maiden Stratigovna peered out the window and spoke
         to Devgenij: "My bright light and beautiful sun! I pity you, my lord, that you wish to
         perish on account of your love for me,</p>
   </div>
   <div id="a22">
      <p>
      <span class="anchor_label">(22) </span>
      <span class="page">[10r] </span>for many have laid down their heads on my account, even without seeing me and
         never having spoken a word with me. And who are you who has determined on such a brazen
         deed?</p>
   </div>
   <div id="a23">
      <p>
      <span class="anchor_label">(23) </span>
      <span class="page">[10r] </span>My father is, you know, exceptionally brave and my brothers are powerful, and
         my father has many warriors, each of whom can taken on a hundred. And you have so few men
         with you."</p>
   </div>
   <div id="a24">
      <p>
      <span class="anchor_label">(24) </span>
      <span class="page">[10r] </span>Devgenij answered the maiden: If I did not fear God, then I would commit
            you to death. But answer me quickly what is in your thoughts: do you wish to become the
            wife of Devgenij Akrit or do you wish to be a captive — a servant?
      </p>
   </div>
   <div id="a25">
      <p>
      <span class="anchor_label">(25) </span>
      <span class="page">[10r] </span>When she heard this, the girl answered him tearfully: "If you love me so
         strongly, then quickly abduct me while neither my father <span class="page">[10v] </span> and nor my mighty
         brothers are at home.</p>
   </div>
   <div id="a26">
      <p>
      <span class="anchor_label">(26) </span>
      <span class="page">[10v] </span>But why must you abduct me? I wish go off with you myself, only dress me in
         men's clothing.</p>
   </div>
   <div id="a27">
      <p>
      <span class="anchor_label">(27) </span>
      <span class="page">[10v] </span>For I have the daring of a man!</p>
   </div>
   <div id="a28">
      <p>
      <span class="anchor_label">(28) </span>
      <span class="page">[10v] </span>If they catch up to me along the way, I will not disgrace myself. Many have
         been unable to overcome me."</p>
   </div>
   <div id="a31">
      <p>
      <span class="anchor_label">(31) </span>
      <span class="page">[13r] </span> When he had heard this, Devgenij kissed her and rode out against them, and
         he met them far out in the field.</p>
   </div>
   <div id="a32">
      <p>
      <span class="anchor_label">(32) </span>
      <span class="page">[13r] </span>He struck like a strong falcon at the center of the army, like a good mower
         he cut them down like grass: he galloped through them once and killed seven thousand; he
         returned and killed twenty thousand.</p>
   </div>
   <div id="a33">
      <p>
      <span class="anchor_label">(33) </span>
      <span class="page">[13r] </span>A third time he galloped and he caught up to Stratig. He hit him lightly with
         his club <span class="page">[13v] </span> on the top of his helmet and knocked him from his horse.</p>
   </div>
   <div id="a34">
      <p>
      <span class="anchor_label">(34) </span>
      <span class="page">[13v] </span>And Stratig began imploring Devgenij:</p>
   </div>
   <div id="a35">
      <p>
      <span class="anchor_label">(35) </span>
      <span class="page">[13v] </span>
         Be content with the abducted maiden, my beautiful daughter. Let me live!
      </p>
   </div>
   <div id="a36">
      <p>
      <span class="anchor_label">(36) </span>
      <span class="page">[13v] </span>And Devgenij let him go but he caught up to his sons, bound them, and led
         them off with him.</p>
   </div>
   <div id="a37">
      <p>
      <span class="anchor_label">(37) </span>
      <span class="page">[13v] </span>He did not tie up Stratig.</p>
   </div>
   <div id="a38">
      <p>
      <span class="anchor_label">(38) </span>
      <span class="page">[13v] </span>And binding the army, he drove them before him like a shepherd a flock of
         sheep to where the maiden was standing.</p>
   </div>
   <div id="a39">
      <p>
      <span class="anchor_label">(39) </span>
      <span class="page">[13v] </span>And she saw her father and said: That is what I told you, father, but you
            would not believe me.
      </p>
   </div>
   <div id="a40">
      <p>
      <span class="anchor_label">(40) </span>
      <span class="page">[13v] </span>And Devgenij ordered his servants to drive the bound warriors of Stratig and
         he led Stratig himself and his sons along with him.</p>
   </div>
   <div id="a41">
      <p>
      <span class="anchor_label">(41) </span>
      <span class="page">[13v] </span>And so then Stratig grew sad and together with his sons began to plead with
         Devgenij, saying to him:</p>
   </div>
   <div id="a42">
      <p>
      <span class="anchor_label">(42) </span>
      <span class="page">[13v] </span>
         You did not condemn us to death but granted us life, so do not cart us off with you but
            return us our liberty.
      </p>
   </div>
   <div id="a43">
      <p>
      <span class="anchor_label">(43) </span>
      <span class="page">[13v] </span>And the maiden heard the pleading of her father and brothers and she began
         asking Devgenij:</p>
   </div>
   <div id="a44">
      <p>
      <span class="anchor_label">(44) </span>
      <span class="page">[14r] </span>"I was given into your hands by God.</p>
   </div>
   <div id="a45">
      <p>
      <span class="anchor_label">(45) </span>
      <span class="page">[14r] </span>You are the ruler not only of me but also of my family. You have defeated
         many warriors already but give my father and brothers back their liberty, do not grieve my
         mother who nursed your wife." And as the maiden spoke this way,</p>
   </div>
   <div id="a46">
      <p>
      <span class="anchor_label">(46) </span>
      <span class="page">[14r] </span>Devgenij heeded her and said to Stratig: I shall have mercy on your age
            and grant you and your sons freedom, but I shall place my brand upon you.
      </p>
   </div>
   <div id="a51">
      <p>
      <span class="anchor_label">(51) </span>
      <span class="page">[14v] </span>When he had returned to his own country, he sent his trusted servants with
         great ceremony to his father and mother with the news and requested of them that they
         prepare a glorious wedding. And he said to his father:</p>
   </div>
   <div id="a52">
      <p>
      <span class="anchor_label">(52) </span>
      <span class="page">[14v] </span>"You, father, were formerly famed for your strength and glory, and now I,
         with the help of God and your blessing and the prayers of my mother, what I conceived of
         has all come true.</p>
   </div>
   <div id="a53">
      <p>
      <span class="anchor_label">(53) </span>
      <span class="page">[14v] </span>I have no opponent. Stratig alone was stronger than all knights, but with
         God's help he could not stand against me, for I abducted his daughter.</p>
   </div>
   <div id="a54">
      <p>
      <span class="anchor_label">(54) </span>
      <span class="page">[14v] </span>And now, father, with great honors come out to greet me and Stratigovna."</p>
   </div>
   <div id="a55">
      <p>
      <span class="anchor_label">(55) </span>
      <span class="page">[14v] </span>And his runners came to him and told the father all that Devgenij had told
         them to say.</p>
   </div>
   <div id="a56">
      <p>
      <span class="anchor_label">(56) </span>
      <span class="page">[14v] </span>And upon hearing this, his father and mother rejoiced <span class="page">[15r] </span> and
         began preparing for the wedding, and they summoned the entire city and they went out to
         meet Devgenij and Stratigovna, and they met them eight versts from the city with great
         honors.</p>
   </div>
   <div id="a57">
      <p>
      <span class="anchor_label">(57) </span>
      <span class="page">[15r] </span>And all knelt down before Devgenij, exclaiming: O great is the miracle
            accomplished by you, a young lad, o noble is your daring! You have defeated Stratig and
            abducted his daughter!
      </p>
   </div>
   <div id="a58">
      <p>
      <span class="anchor_label">(58) </span>
      <span class="page">[15r] </span>And Devgenij replied: It was not I who defeated the force of Stratig; he
            was defeated by the force of God!
      </p>
   </div>
   <div id="a61">
      <p>
      <span class="anchor_label">(61) </span>
      <span class="page">[16r] </span>So Devgenij returned home, having seen Stratig off, and he freed all the
         captives.</p>
   </div>
   <div id="a62">
      <p>
      <span class="anchor_label">(62) </span>
      <span class="page">[16r] </span>And he branded his uncle Filipap on the face and then sent him off to where
         he had come from,</p>
   </div>
   <div id="a63">
      <p>
      <span class="anchor_label">(63) </span>
      <span class="page">[16r] </span>and Maksimijana's liberation he announced through his servants.</p>
   </div>
   <div id="a64">
      <p>
      <span class="anchor_label">(64) </span>
      <span class="page">[16r] </span>And then he began living and prospering and going hunting, for he loved these
         bogatyr's pursuits.</p>
   </div>
   <div id="adox">
      <p>
      <span class="anchor_label">(dox) </span>
      <span class="page">[16r] </span>Oh, what a great miracle, brothers! Who would not be astonished at it? He was
         an unusual man and he became such not from Amir but he was sent down by God. All brave
         Christians learned of his glory, and he was made famous throughout all the world with the
         aid of our Lord Jesus Christ, to whom glory with the Father and the Holy Spirit now and
         forevermore and in eternity, and to the ages of ages. Amen.</p>
   </div>

