
    <div id="c0">
        <p>
      <span class="anchor_label">(0) </span>When the child (Alexander) was born and came into the light, he
            cried and said: In my 40th year I will return to you again, mother!<span class="anchor_label"> [1.3.4]</span>
   </p>
    </div>
    <div id="c1">
        <p>
      <span class="anchor_label">(1) </span>Having come near (the Amazons') city, (Alexander) stopped there
            with his retinue. And waiting there, he sent them a letter containing the following:
                Alexander, king of kings, sends to Talistris, the Amazon queen …<span class="anchor_label"> [4.103.3]</span>
   </p>
    </div>
    <div id="c2">
        <p>
      <span class="anchor_label">(2) </span>Then Queen Talistris received Alexander's letter, read it, and
            wrote a letter back to Alexander as follows:<span class="anchor_label"> [4.103.16]</span>
   </p>
    </div>
    <div id="c3">
        <p>
      <span class="anchor_label">(3) </span>If you wish to learn how we abide, let us show you in this
            letter:<span class="anchor_label"> [4.103.23]</span>
   </p>
    </div>
    <div id="c4">
        <p>
      <span class="anchor_label">(4) </span>If you kill us, you will not achieve any fame, for you will
            have killed women.<span class="anchor_label"> [4.103.46]</span>
   </p>
    </div>
    <div id="c5">
        <p>
      <span class="anchor_label">(5) </span>If you will come to us in battle, send to us quickly: we will
            meet you at the foot of the mountains!<span class="anchor_label"> [4.103.47]</span>
   </p>
    </div>
    <div id="c6">
        <p>
      <span class="anchor_label">(6) </span>Alexander read the letter before all his horsemen. And
            Alexander laughed greatly at it and had a letter written containing the following:<span class="anchor_label"> [4.103.50]</span>
   </p>
    </div>
    <div id="c7">
        <p>
      <span class="anchor_label">(7) </span>If you do not want to perish, consider well your lives and give
            us tribute and send us some of your horsewomen, so that we may see them and receive them
            with joy and honor them well.<span class="anchor_label"> [4.103.59]</span>
   </p>
    </div>
    <div id="c8">
        <p>
      <span class="anchor_label">(8) </span>Then Queen Talistris sent Alexander … precious gifts and a
            letter containing the following:<span class="anchor_label"> [4.103.64]</span>
   </p>
    </div>
    <div id="c9">
        <p>
      <span class="anchor_label">(9) </span>A rumor has come to our ears … that, having taken all the
            world, you want to fight a women's army … It is not fitting for you to fight us.<span class="anchor_label"> [4.103.70]</span>
   </p>
    </div>
    <div id="c10">
        <p>
      <span class="anchor_label">(10) </span>For if you destroy us, you will achieve little honor; if we
            destroy you, this will be a great disgrace for you.<span class="anchor_label"> [4.103.75]</span>
   </p>
    </div>
    <div id="c11">
        <p>
      <span class="anchor_label">(11) </span>Have mercy on us and accept the small offerings of your
            faithful servants and write back with hope (for us) soon!<span class="anchor_label"> [4.103.84]</span>
   </p>
    </div>
    <div id="c12">
        <p>
      <span class="anchor_label">(12) </span>Alexander laughed … and said (to Ptolemy): Even if you are
                the general of (all) my forces, (a single) one of those women can overcome
            you.<span class="anchor_label"> [4.103.106]</span>
   </p>
    </div>


