
    <div id="c0">
        <p>
      <span class="anchor_label">(0) </span>Alexander asked (Sesonchosis), "How many years will I live?" He
            replied, "It is good for a living man not to know when he is to die."<span class="anchor_label"> [3.24]</span>
   </p>
    </div>
    <div id="c1">
        <p>
      <span class="anchor_label">(1) </span>From there (Alexander) marched to the Amazons; and when he had
            reached them, he sent them a letter with the following contents.<span class="anchor_label"> [3.25]</span>
   </p>
    </div>
    <div id="c2">
        <p>
      <span class="anchor_label">(2) </span>"We are marching on you. Meet us with joy; we do not come to do you
            ill, but to see your country and at the same time do you good."<span class="anchor_label"> [3.25]</span>
   </p>
    </div>
    <div id="c3">
        <p>
      <span class="anchor_label">(3) </span>Receiving Alexander's letter and reading it, (the leading Amazons)
            wrote Alexander this reply.<span class="anchor_label"> [3.25]</span>
   </p>
    </div>
    <div id="c4">
        <p>
      <span class="anchor_label">(4) </span>"By our letter we shall make clear the nature of our country and of
            ourselves, who have a way of life to be reckoned with."<span class="anchor_label"> [3.25]</span>
   </p>
    </div>
    <div id="c5">
        <p>
      <span class="anchor_label">(5) </span>"If we defeat the enemy … a terrible disgrace stays with them for
            all time; but if they defeat us, they will be in a situation of having defeated
            women."<span class="anchor_label"> [3.25]</span>
   </p>
    </div>
    <div id="c6">
        <p>
      <span class="anchor_label">(6) </span>Alexander read (the Amazons') letter and with a smile (a laugh)
            wrote them this reply.<span class="anchor_label"> [3.26]</span>
   </p>
    </div>
    <div id="c7">
        <p>
      <span class="anchor_label">(7) </span>"If you want to live in your own land rather than try your luck in
            battle, cross your river and be seen by us."<span class="anchor_label"> [3.26]</span>
   </p>
    </div>
    <div id="c8">
        <p>
      <span class="anchor_label">(8) </span>On receiving and reading Alexander's letter, (the Amazons) … wrote
            him this reply.<span class="anchor_label"> [3.26]</span>
   </p>
    </div>
    <div id="c9">
        <p>
      <span class="anchor_label">(9) </span>"We give you permission to come to us and see our country."<span class="anchor_label"> [3.26]</span>
   </p>
    </div>
    <div id="c10">
        <p>
      <span class="anchor_label">(10) </span>"We accept allegiance to you, in your presence and in your absence:
            we have heard of your exceptional qualities and your bravery."<span class="anchor_label"> [3.26]</span>
   </p>
    </div>
    <div id="c11">
        <p>
      <span class="anchor_label">(11) </span>"We have decided … to be subject to you as master."<span class="anchor_label"> [3.26]</span>
   </p>
    </div>
    <div id="c12">
        <p>
      <span class="anchor_label">(12) </span>After this exchange of letters, Alexander wrote his mother,
            Olympias, this account of his deeds.<span class="anchor_label"> [3.27]</span>
   </p>
    </div>
    <div id="c13">
        <p>
      <span class="anchor_label">(13) </span>"… the Amazons (are) women of exceptional height, much taller than
            other women, notable for their attractiveness and strength."<span class="anchor_label"> [3.27]</span>
   </p>
    </div>


