
   <p>
   <span class="page">[16r] </span>
   <cite>The Tale of How Devgenij Defeated Tsar Vasilij</cite>
</p>
<div id="e1">
   <p>
      <span class="anchor_label">(1) </span>
      <span class="page">[16r] </span>There was a certain tsar named Vasilij. And he became extremely angry,
         hearing of the daring and bravery of Devgenij, and he burned with the desire to capture him 
      </p>
</div>
<div id="e2">
   <p>
      <span class="anchor_label">(2) </span>
      <span class="page">[16r] </span>for tsar Vasilij controlled all the land of Cappadocia.</p>
</div>
<div id="e3">
   <p>
      <span class="anchor_label">(3) </span>
      <span class="page">[16r] </span>And so he equipped his envoys and sent off an epistle to Devgenij and with
         feigned cordiality <span class="page">[16v] </span> he wrote thus: 
      </p>
</div>
<div id="e4">
   <p>
      <span class="anchor_label">(4) </span>
      <span class="page">[16v] </span>
         Famed Devgenij! I very much want to see you. Do not hesitate now to visit my tsardom;
            your daring and courage have resounded over all the earth.
      </p>
</div>
<div id="e5">
   <p>
      <span class="anchor_label">(5) </span>
      <span class="page">[16v] </span>
         And I have come to love you with all my soul, and I wish to gaze upon your youth.
      </p>
</div>
<div id="e6">
   <p>
      <span class="anchor_label">(6) </span>
      <span class="page">[16v] </span>They delivered the royal epistle to Devgenij, and Devgenij read it and
         understood that the epistle to him was false.</p>
</div>
<div id="e7">
   <p>
      <span class="anchor_label">(7) </span>
      <span class="page">[16v] </span>And Devgenij answered the tsar: I am a simple man. Your royal highness has
            no need of anything from me,
      </p>
</div>
<div id="e8">
   <p>
      <span class="anchor_label">(8) </span>
      <span class="page">[16v] </span>
         but if you wish to see me, then take a small number of warriors with you and come to the
            River Euphrates.
      </p>
</div>
<div id="e9">
   <p>
      <span class="anchor_label">(9) </span>
      <span class="page">[16v] </span>And then he ordered the envoys to say to their tsar: If you wish to see
            me, an unworthy one, then take a few warriors with you, so as not to anger me, for youth
            brings many irrational acts with it.
      </p>
</div>
<div id="e10">
   <p>
      <span class="anchor_label">(10) </span>
      <span class="page">[16v] </span>
         And if I should become angry and destroy your army, then you will not return alive!
      </p>
</div>
<div id="e11">
   <p>
      <span class="anchor_label">(11) </span>
      <span class="page">[16v] </span>So they rode back and the envoy transmitted all that Devgenij had said. When
         he heard this, the tsar became extremely angry and sent the envoy back to Devgenij with the
         words:</p>
</div>
<div id="e12">
   <p>
      <span class="anchor_label">(12) </span>
      <span class="page">[16v] </span>
         My child! I do not wish to bring many warriors with me but only to admire your youth. I
            have nothing else in my heart.
      </p>
</div>
<div id="e13">
   <p>
      <span class="anchor_label">(13) </span>
      <span class="page">[16v] </span>The royal envoy came to Devgenij and related all that had been said by the
         tsar and Devgenij answered him: Tell your tsar this:
      </p>
</div>
<div id="e14">
   <p>
      <span class="anchor_label">(14) </span>
      <span class="page">[16v] </span>
         I do not fear <span class="page">[17r] </span> you, tsar, nor your innumerable army, for I place my
            hopes on God.
      </p>
</div>
<div id="e15">
   <p>
      <span class="anchor_label">(15) </span>
      <span class="page">[17r] </span>
         I do not fear your evil plot but I say to you:
      </p>
</div>
<div id="e16">
   <p>
      <span class="anchor_label">(16) </span>
      <span class="page">[17r] </span>
         Come to the River Euphrates and you and I shall see each other.
      </p>
</div>
<div id="e17">
   <p>
      <span class="anchor_label">(17) </span>
      <span class="page">[17r] </span>
         If you come with a large force, then you will not rejoice in the fact that you rule, and
            your entire force will be destroyed.
      </p>
</div>
<div id="e18">
   <p>
      <span class="anchor_label">(18) </span>
      <span class="page">[17r] </span>And the envoy came to tsar Vasilij and related the words of Devgenij to
         him.</p>
</div>
<div id="e19">
   <p>
      <span class="anchor_label">(19) </span>
      <span class="page">[17r] </span>When he had heard this, the tsar immediately ordered his warriors summoned
         and having gathered them together, he moved off with that force to the place indicated by
         Devgenij. And having come to the River Euphrates, he set up his tents at some distance from
         the river. 
      </p>
</div>
<div id="e20">
   <p>
      <span class="anchor_label">(20) </span>
      <span class="page">[17r] </span>And the royal pavilion was enormous, bright red in color, and the top of it
         was sewn in pure gold; and inside the tent were quartered several thousand warriors. And
         the entire force of the tsar was covered: some in tents and other in sheltered places.</p>
</div>
<div id="e21">
   <p>
      <span class="anchor_label">(21) </span>
      <span class="page">[17r] </span>And the tsar stayed for six days on the river and he said to his voevodas:
            Devgenij has found out something and contrived something against us for he himself
            intends to come with a large force.
      </p>
</div>
<div id="e22">
   <p>
      <span class="anchor_label">(22) </span>
      <span class="page">[17r] </span>And having said this, tsar Vasilij shook from fear.</p>
</div>
<div id="e23">
   <p>
      <span class="anchor_label">(23) </span>
      <span class="page">[17r] </span>And Devgenij sent a servant to the tsar with these words:</p>
</div>
<div id="e24">
   <p>
      <span class="anchor_label">(24) </span>
      <span class="page">[17r] </span>
         I am amazed that you have put forth so much labor <span class="page">[17v] </span> on my account as I am
            nothing.
      </p>
</div>
<div id="e25">
   <p>
      <span class="anchor_label">(25) </span>
      <span class="page">[17v] </span>
         But I already told you of my custom: if you wish to meet me, then come with a small
            detachment.
      </p>
</div>
<div id="e26">
   <p>
      <span class="anchor_label">(26) </span>
      <span class="page">[17v] </span>
         But you have gathered an enormous army thinking to defeat me,
      </p>
</div>
<div id="e27">
   <p>
      <span class="anchor_label">(27) </span>
      <span class="page">[17v] </span>
         and that is disgraceful, for my fame has gone throughout all the earth and to all lands.
            And so now do as you have intended to do.
      </p>
</div>
<div id="e28">
   <p>
      <span class="anchor_label">(28) </span>
      <span class="page">[17v] </span>Tsar Vasilij answered: How dare you that you do not wish to submit to me,
            a tsar! And fitting out his envoy, he sent him across the river and received
         Devgenij's envoy.</p>
</div>
<div id="e29">
   <p>
      <span class="anchor_label">(29) </span>
      <span class="page">[17v] </span>And the royal envoy came to transmit the royal words to Devgenij.</p>
</div>
<div id="e30">
   <p>
      <span class="anchor_label">(30) </span>
      <span class="page">[17v] </span>And Devgenij replied; Tell your tsar: if he is relying on his great force,
            then I hope on God the Creator. And your force cannot compare with the might of God.
      </p>
</div>
<div id="e31">
   <p>
      <span class="anchor_label">(31) </span>
      <span class="page">[17v] </span>
         This day is nearly over but prepare for battle as of tomorrow morning, and come forth
            with your innumerable force and you will see the courage of an insignificant man who
            will appear before you; otherwise, I will be shamed for that which is not
            undertaken.
      </p>
</div>
<div id="e32">
   <p>
      <span class="anchor_label">(32) </span>
      <span class="page">[17v] </span>And the envoy of tsar Vasilij came back from Devgenij and told his words
            <span class="page">[18r] </span> to the tsar.</p>
</div>
<div id="e33">
   <p>
      <span class="anchor_label">(33) </span>
      <span class="page">[18r] </span>The tsar quickly called his boyars and began taking counsel with them, and
         the magnates said to him: What is your rule worth, tsar, if you are afraid of a single
            warrior – no forces are seen with him.
      </p>
</div>
<div id="e34">
   <p>
      <span class="anchor_label">(34) </span>
      <span class="page">[18r] </span>And Devgenij's envoy hurried across the river and told Devgenij all that had
         occurred with the tsar.</p>
</div>
<div id="e35">
   <p>
      <span class="anchor_label">(35) </span>
      <span class="page">[18r] </span>The next day at daybreak tsar Vasilij placed his forces and got ready to
         cross over the river</p>
</div>
<div id="e36">
   <p>
      <span class="anchor_label">(36) </span>
      <span class="page">[18r] </span>to catch Devgenij like a hare in a trap.</p>
</div>
<div id="e37">
   <p>
      <span class="anchor_label">(37) </span>
      <span class="page">[18r] </span>Devgenij saw that tsar Vasilij had prepared an innumerable force, and he
         guessed that when he had crossed the river, he would surround him.</p>
</div>
<div id="e38">
   <p>
      <span class="anchor_label">(38) </span>
      <span class="page">[18r] </span>Furious, Devgenij said to his servants: Join me in a little while, first I
            shall myself undertake some little labor and serve that tsar.
      </p>
</div>
<div id="e39">
   <p>
      <span class="anchor_label">(39) </span>
      <span class="page">[18r] </span>And having said these words, he propped himself up with his lance and leapt
         across the river like a strong falcon,</p>
</div>
<div id="e40">
   <p>
      <span class="anchor_label">(40) </span>
      <span class="page">[18r] </span>and he shouted at the top of his lungs: Where is this tsar Vasilij who
            wanted to see something of me?
      </p>
</div>
<div id="e41">
   <p>
      <span class="anchor_label">(41) </span>
      <span class="page">[18r] </span>He shouted and immediately the warriors rushed at him, and he stuck his lance
         in the ground and rushed at the warriors with his bare sword.</p>
</div>
<div id="e42">
   <p>
      <span class="anchor_label">(42) </span>
      <span class="page">[18r] </span>And he galloped up and like a good mower cutting grass, the first time he
         galloped through, he defeated a thousand, then he came back and galloped through them
         again, and another <span class="page">[18v] </span> thousand he defeated.</p>
</div>
<div id="e43">
   <p>
      <span class="anchor_label">(43) </span>
      <span class="page">[18v] </span>Tsar Vasilij saw the courage of Devgenij and with but a handful of his men
         fled.</p>
</div>
<div id="e44">
   <p>
      <span class="anchor_label">(44) </span>
      <span class="page">[18v] </span>Devgenij killed the remaining warriors and then bound up the remainder</p>
</div>
<div id="e45">
   <p>
      <span class="anchor_label">(45) </span>
      <span class="page">[18v] </span>and shouted to his servants across the river: Bring that swift horse of
            mine, the one called Wind.
      </p>
</div>
<div id="e46">
   <p>
      <span class="anchor_label">(46) </span>
      <span class="page">[18v] </span>They drove the horse over to him,</p>
</div>
<div id="e47">
   <p>
      <span class="anchor_label">(47) </span>
      <span class="page">[18v] </span>he mounted it and tore off and soon caught up to tsar Vasilij at the walls of
         his city,</p>
</div>
<div id="e48">
   <p>
      <span class="anchor_label">(48) </span>
      <span class="page">[18v] </span>and he killed all the warriors who were with him, and took the tsar and three
         of his companions captive.</p>
</div>
<div id="e49">
   <p>
      <span class="anchor_label">(49) </span>
      <span class="page">[18v] </span>And he sent one of them into the city with the news. And he said to the
         citizens:</p>
</div>
<div id="e50">
   <p>
      <span class="anchor_label">(50) </span>
      <span class="page">[18v] </span>
         Come out to meet Devgenij; from this day on God has granted it that he will rule in your
            country.
      </p>
</div>
<div id="e51">
   <p>
      <span class="anchor_label">(51) </span>
      <span class="page">[18v] </span>When the heard this, they gathered together and came out to fight with him
         before the city, thinking that they would be fighting with an ordinary man.</p>
</div>
<div id="e52">
   <p>
      <span class="anchor_label">(52) </span>
      <span class="page">[18v] </span>And he sent a message to them, saying: Put down your weapons and do not
            anger me.
      </p>
</div>
<div id="e53">
   <p>
      <span class="anchor_label">(53) </span>
      <span class="page">[18v] </span>They replied: A single man cannot stand against our entire city.
      </p>
</div>
<div id="e54">
   <p>
      <span class="anchor_label">(54) </span>
      <span class="page">[18v] </span>When he heard their reply, Devgenij grew angry and rushed at them:</p>
</div>
<div id="e55">
   <p>
      <span class="anchor_label">(55) </span>
      <span class="page">[18v] </span>some he killed, others he bound and handed over to his servants, and then he
         entered the city and began ruling there.</p>
</div>
<div id="e56">
   <p>
      <span class="anchor_label">(56) </span>
      <span class="page">[19r] </span>And he soon freed the captives, as it says in scripture: The servant
            cannot be greater than his master, nor the son greater than his father.
      </p>
</div>
<div id="e57">
   <p>
      <span class="anchor_label">(57) </span>
      <span class="page">[19r] </span>
         But I still have twelve years to live and now I wish to rest, I have seen many wars and
            victories in my youth,
      </p>
</div>
<div id="e58">
   <p>
      <span class="anchor_label">(58) </span>
      <span class="page">[19r] </span>so spoke Devgenij to his father and he sat him on the royal throne and he
         summoned all his captives and gave them their freedom.</p>
</div>
<div id="e59">
   <p>
      <span class="anchor_label">(59) </span>
      <span class="page">[19r] </span>And he placed brands on the faces of Kanam and Ioakim and sent them to their
         native country.</p>
</div>
<div id="e60">
   <p>
      <span class="anchor_label">(60) </span>
      <span class="page">[19r] </span>And he summoned all his relatives and shared in their great joy, and thus it
         continued for many days.</p>
</div>
<div id="edox">
   <p>
      <span class="anchor_label">(dox) </span>
      <span class="page">[19r] </span>Glory to our God now and forever and to the ages of ages! Amen.</p>
</div>
