
    <p class="section_title">
        The meadow in May
    <span class="anchor_label"> [E1097–1196; G6.1–175]</span>
</p>
    <div id="g1">
        <p>
      <span class="anchor_label">(1) </span>Rhetorical introduction: Narrator's preamble<span class="anchor_label"> [G6.1–3]</span>
   </p>
    </div>
    <div id="g2">
        <p>
      <span class="anchor_label">(2) </span>Rhetorical introduction: Encomium of May<span class="anchor_label"> [G6.4–11]</span>
   </p>
    </div>
    <div id="g3">
        <p>
      <span class="anchor_label">(3) </span>Rhetorical introduction: Ekphrasis of the meadow and the
            girl<span class="anchor_label"> [G6.12–41]</span>
   </p>
    </div>
    <div id="g4">
        <p>
      <span class="anchor_label">(4) </span>Encounter with serpent and lion: Serpent seduces the girl at the
            spring<span class="anchor_label"> [G6.42–62]</span>
   </p>
    </div>
    <div id="g5">
        <p>
      <span class="anchor_label">(5) </span>Encounter with the serpent and the lion: Digenis
            kills the serpent at the spring<span class="anchor_label"> [E1097–1119; G6.63–85]</span>
   </p>
    </div>
    <div id="g6">
        <p>
      <span class="anchor_label">(6) </span>Encounter with the serpent and the lion: Digenis
            kills the lion at the spring<span class="anchor_label"> [E1120–1138; G6.86–97]</span>
   </p>
    </div>
    <div id="g7">
        <p>
      <span class="anchor_label">(7) </span>Encounter with the serpent and the lion: Digenis
            plays the lute, the girl sings<span class="anchor_label"> [E1139–1150; G6.98–114]</span>
   </p>
    </div>
    <div id="g8">
        <p>
      <span class="anchor_label">(8) </span>The guerrillas encounter Digenis<span class="anchor_label"> [E1151–1196; G6.115–175]</span>
   </p>
    </div>
    <p class="section_title">
        Digenis defeats Philopappous, Kinnamos, and
            Ioannakis
    <span class="anchor_label"> [E1197–1315; G6.176–310]</span>
</p>
    <p class="section_title">
        The guerrillas summon Maximou and Melimitzis
    <span class="anchor_label"> [E1316–1420; G6.311–475]</span>
</p>
    <p class="section_title">
        Digenis defeats the guerrillas and Maximou
    <span class="anchor_label"> [E1421–1553; G6.476–713]</span>
</p>
    <div id="g31">
        <p>
      <span class="anchor_label">(31) </span>The guerrillas take counsel<span class="anchor_label"> [E1421–1438; G6.476–496]</span>
   </p>
    </div>
    <div id="g33">
        <p>
      <span class="anchor_label">(33) </span>The guerrillas attack Digenis: Digenis unhorses
            Melimitzis (with a strike between the shoulders)<span class="anchor_label"> [E1439–1450; G6.497–507]</span>
   </p>
    </div>
    <div id="g34">
        <p>
      <span class="anchor_label">(34) </span>The guerrillas attack Digenis: Philopappous
            spears Digenis from behind<span class="anchor_label"> [E1451–1460; G6.508–516]</span>
   </p>
    </div>
    <div id="g35">
        <p>
      <span class="anchor_label">(35) </span>The guerrillas attack Digenis: Philopappous and Kinnamos<span class="anchor_label"> [G6.516–522]</span>
   </p>
    </div>
    <div id="g36">
        <p>
      <span class="anchor_label">(36) </span>Digenis hides the girl<span class="anchor_label"> [E1461–1481; G6.523–545]</span>
   </p>
    </div>
    <div id="g39">
        <p>
      <span class="anchor_label">(39) </span>Maximou observes Digenis: Maximou
            with the guerrillas<span class="anchor_label"> [E1482–1485, 1497–1500; G6.546–549]</span>
   </p>
    </div>
    <div id="g40">
        <p>
      <span class="anchor_label">(40) </span>Maximou observes Digenis: Ekphrasis of
            Maximou<span class="anchor_label"> [E1486–1496; G6.550–556]</span>
   </p>
    </div>
    <div id="g41">
        <p>
      <span class="anchor_label">(41) </span>Maximou observes Digenis: Maximou sees Digenis
            and is angered<span class="anchor_label"> [E1501–1527; G6.557–568]</span>
   </p>
    </div>
    <div id="g42">
        <p>
      <span class="anchor_label">(42) </span>Digenis crosses to defeat Maximou<span class="anchor_label"> [E1528–1547; G6.569–617]</span>
   </p>
    </div>
    <div id="g45">
        <p>
      <span class="anchor_label">(45) </span>Digenis defeats four guerrillas<span class="anchor_label"> [G6.618–643]</span>
   </p>
    </div>
    <div id="g48">
        <p>
      <span class="anchor_label">(48) </span>Digenis and Maximou arrange single combat<span class="anchor_label"> [E1548–1553; G6.644–713]</span>
   </p>
    </div>
    <p class="section_title">
        Digenis defeats Maximou again and commits
            adultery
    <span class="anchor_label"> [E1554–1605; G6.714–805]</span>
</p>
    <div id="g51">
        <p>
      <span class="anchor_label">(51) </span>Digenis defeats Maximou in single combat: Digenis returns to
            his tent<span class="anchor_label"> [G6.714–729]</span>
   </p>
    </div>
    <div id="g52">
        <p>
      <span class="anchor_label">(52) </span>Digenis defeats Maximou in single combat: Ekphrasis of
            Maximou<span class="anchor_label"> [G6.730–739]</span>
   </p>
    </div>
    <div id="g53">
        <p>
      <span class="anchor_label">(53) </span>Digenis defeats Maximou in single combat:
            Digenis unhorses Maximou<span class="anchor_label"> [E1554–1561; G6.740–763]</span>
   </p>
    </div>
    <div id="g54">
        <p>
      <span class="anchor_label">(54) </span>Digenis defeats Maximou in single combat:
            Maximou offers Digenis alliance<span class="anchor_label"> [E1562–1573; G6.764–776]</span>
   </p>
    </div>
    <div id="g55">
        <p>
      <span class="anchor_label">(55) </span>Digenis deflowers Maximou<span class="anchor_label"> [E1574–1577; G6.777–Z.3720]</span>
   </p>
    </div>
    <div id="g57">
        <p>
      <span class="anchor_label">(57) </span>Digenis returns to the girl<span class="anchor_label"> [E1578–1599; GZ.3721–6.802]</span>
   </p>
    </div>
    <div id="g60">
        <p>
      <span class="anchor_label">(60) </span>Maximou's men, Kinnamos, Ioannakis, and Philopappous
            scatter<span class="anchor_label"> [E1600–1605]</span>
   </p>
    </div>

