
    <p class="section_title">
        The meadow in May
    <span class="anchor_label"> [E1097–1196; G6.1–175]</span>
</p>
    <div id="ga">
        <p>
      <span class="anchor_label">(a) </span>Rhetorical introduction: Narrator's preamble<span class="anchor_label"> [G6.1–3]</span>
   </p>
    </div>
    <div id="gb">
        <p>
      <span class="anchor_label">(b) </span>Rhetorical introduction: Encomium of May<span class="anchor_label"> [G6.4–11]</span>
   </p>
    </div>
    <div id="gc">
        <p>
      <span class="anchor_label">(c) </span>Rhetorical introduction: Ekphrasis of the meadow and the
            girl<span class="anchor_label"> [G6.12–41]</span>
   </p>
    </div>
    <div id="gd">
        <p>
      <span class="anchor_label">(d) </span>Encounter with serpent and lion: Serpent seduces the girl at the
            spring<span class="anchor_label"> [G6.42–62]</span>
   </p>
    </div>
    <div id="ge">
        <p>
      <span class="anchor_label">(e) </span>Encounter with the serpent and the lion: Digenis
            kills the serpent at the spring<span class="anchor_label"> [E1097–1119; G6.63–85]</span>
   </p>
    </div>
    <div id="gf">
        <p>
      <span class="anchor_label">(f) </span>Encounter with the serpent and the lion: Digenis
            kills the lion at the spring<span class="anchor_label"> [E1120–1138; G6.86–97]</span>
   </p>
    </div>
    <div id="gg">
        <p>
      <span class="anchor_label">(g) </span>Encounter with the serpent and the lion: Digenis
            plays the lute, the girl sings<span class="anchor_label"> [E1139–1150; G6.98–114]</span>
   </p>
    </div>
    <div id="gh">
        <p>
      <span class="anchor_label">(h) </span>The guerrillas encounter Digenis<span class="anchor_label"> [E1151–1196; G6.115–175]</span>
   </p>
    </div>
    <p class="section_title">
        Digenis defeats Philopappous, Kinnamos, and
            Ioannakis
    <span class="anchor_label"> [E1197–1315; G6.176–310]</span>
</p>
    <p class="section_title">
        The guerrillas summon Maximou and Melimitzis
    <span class="anchor_label"> [E1316–1420; G6.311–475]</span>
</p>
    <p class="section_title">
        Digenis defeats the guerrillas and Maximou
    <span class="anchor_label"> [E1421–1553; G6.476–713]</span>
</p>
    <div id="g9">
        <p>
      <span class="anchor_label">(9) </span>Digenis keeps watch for the guerrillas<span class="anchor_label"> [E1421–1429; G6.476–478]</span>
   </p>
    </div>
    <div id="g10">
        <p>
      <span class="anchor_label">(10) </span>The guerrillas' comments before the attack<span class="anchor_label"> [E1430–1434; G6.479–488]</span>
   </p>
    </div>
    <div id="g11">
        <p>
      <span class="anchor_label">(11) </span>Melimitzis will not accept that he cannot fight
            the abductor on his own<span class="anchor_label"> [E1435–1438; G6.489–496]</span>
   </p>
    </div>
    <div id="g12">
        <p>
      <span class="anchor_label">(12) </span>The guerrillas attack Digenis: Digenis unhorses
            Melimitzis (with a strike between the shoulders)<span class="anchor_label"> [E1439–1450; G6.497–507]</span>
   </p>
    </div>
    <div id="g12bis">
        <p>
      <span class="anchor_label">(12bis) </span>The guerrillas attack Digenis: Philopappous
            spears Digenis from behind<span class="anchor_label"> [E1451–1460; G6.508–516]</span>
   </p>
    </div>
    <div id="g13">
        <p>
      <span class="anchor_label">(13) </span>The guerrillas attack Digenis: Philopappous and Kinnamos<span class="anchor_label"> [G6.517–522]</span>
   </p>
    </div>
    <div id="g13bis">
        <p>
      <span class="anchor_label">(13bis) </span>Digenis converses with and hides the girl<span class="anchor_label"> [E1461–1481; G6.523–543]</span>
   </p>
    </div>
    <div id="g14">
        <p>
      <span class="anchor_label">(14) </span>Maximou observes Digenis: Maximou
            with the guerrillas<span class="anchor_label"> [E1482–1485, 1497–1500; G6.544–549]</span>
   </p>
    </div>
    <div id="g14bis">
        <p>
      <span class="anchor_label">(14bis) </span>Maximou observes Digenis: Ekphrasis of
            Maximou<span class="anchor_label"> [E1486–1496; G6.550–556]</span>
   </p>
    </div>
    <div id="g15">
        <p>
      <span class="anchor_label">(15) </span>Maximou observes Digenis: Maximou asks where the
            opposing army is, sees Digenis and is angered<span class="anchor_label"> [E1501–1527; G6.557–567]</span>
   </p>
    </div>
    <div id="g16">
        <p>
      <span class="anchor_label">(16) </span>Digenis crosses the river<span class="anchor_label"> [E1528–1540; G6.568–580]</span>
   </p>
    </div>
    <div id="g17">
        <p>
      <span class="anchor_label">(17) </span>Digenis defeats Maximou (and, in G, four
            guerrillas)<span class="anchor_label"> [E1541–1547; G6.581–643]</span>
   </p>
    </div>
    <div id="g17bis">
        <p>
      <span class="anchor_label">(17bis) </span>Maximou asks for a second chance; Digenis and
            Maximou arrange single combat<span class="anchor_label"> [E1548–1551; G6.644–677]</span>
   </p>
    </div>
    <p class="section_title">
        Digenis defeats Maximou again and commits
            adultery
    <span class="anchor_label"> [E1552–1605; G6.678–805]</span>
</p>
    <div id="g18">
        <p>
      <span class="anchor_label">(18) </span>Digenis gets Maximou a second horse<span class="anchor_label"> [E1552–1554; G6.678–684]</span>
   </p>
    </div>
    <div id="g19">
        <p>
      <span class="anchor_label">(19) </span>Digenis fights the guerrillas again, changes clothes and
            awaits the next day<span class="anchor_label"> [G6.685–729]</span>
   </p>
    </div>
    <div id="g19bis">
        <p>
      <span class="anchor_label">(19bis) </span>Digenis defeats Maximou in single combat: Ekphrasis of
            Maximou<span class="anchor_label"> [G6.730–739]</span>
   </p>
    </div>
    <div id="g20">
        <p>
      <span class="anchor_label">(20) </span>Digenis defeats Maximou in single combat:
            Digenis unhorses Maximou<span class="anchor_label"> [E1555–1561; G6.740–763]</span>
   </p>
    </div>
    <div id="g21">
        <p>
      <span class="anchor_label">(21) </span>Digenis defeats Maximou in single combat:
            Maximou offers herself to Digenis<span class="anchor_label"> [E1562–1574; G6.764–776]</span>
   </p>
    </div>
    <div id="g22">
        <p>
      <span class="anchor_label">(22) </span>Digenis deflowers Maximou<span class="anchor_label"> [E1575–1579; G6.777–Z.3720]</span>
   </p>
    </div>
    <div id="g23">
        <p>
      <span class="anchor_label">(23) </span>Digenis justifies himself to the girl<span class="anchor_label"> [E1578–1599; GZ.3721–6.805]</span>
   </p>
    </div>
    <div id="g23bis">
        <p>
      <span class="anchor_label">(23bis) </span>Maximou's men, Kinnamos, Ioannakis, and Philopappous
            scatter<span class="anchor_label"> [E1600–1605]</span>
   </p>
    </div>

