
   <p>
   <cite>
      </cite>
   <span class="page">[181v] </span>
   <cite>An Account of the Bravery of Devgenij: How Filipap and the Maiden Maksimijana
      Sent a Missive</cite>
</p>
<div id="mx">
   <p>
      <span class="anchor_label">(x) </span>
      <span class="page">[32v] </span>[Hunt (Slavic)] And the youth had not finished speaking when the enormous
         serpent came flying up to the stream; it was like a three-headed man and it desired to
         devour people. When he caught sight of it, Devgenij quickly grabbed his sword and went out
         to meet the serpent, and he chopped off three heads and began washing his hands.</p>
</div>
<div id="m1">
   <p>
      <span class="anchor_label">(1) </span>
      <span class="page">[181v] </span>When Filipap and the maiden Maksimijana heard about the bravery and about
         the strength of Devgenij, they began to think how they might catch him</p>
</div>
<div id="m2">
   <p>
      <span class="anchor_label">(2) </span>
      <span class="page">[181v] </span>like a hare in a net.</p>
</div>
<div id="m3">
   <p>
      <span class="anchor_label">(3) </span>
      <span class="page">[181v] </span>Filipap is brave and very strong and has great force;</p>
</div>
<div id="m4">
   <p>
      <span class="anchor_label">(4) </span>
      <span class="page">[181v] </span>the maiden Maksimijana too has manly bravery, her army also.</p>
</div>
<div id="m5">
   <p>
      <span class="anchor_label">(5) </span>
      <span class="page">[181v] </span>And they advanced on glorious Devgenij and came and halted, before they
         reached the Greek city, on the river Euphrates.</p>
</div>
<div id="m6">
   <p>
      <span class="anchor_label">(6) </span>
      <span class="page">[181v] </span>And Maksimijana sent a guileful missive to glorious Devgenij:</p>
</div>
<div id="m7">
   <p>
      <span class="anchor_label">(7) </span>
      <span class="page">[181v] </span>
         O light, brilliant sun, glorious Devgenij, you rule among all of us, the brave and the
            strong,
      </p>
</div>
<div id="m8">
   <p>
      <span class="anchor_label">(8) </span>
      <span class="page">[181v] </span>
         like the month of May among all the months. In the month of May all heavenly and earthly
               beauty flowers; the trees put forth leaves and all heavenly
            beauty is created;
      </p>
</div>
<div id="m9">
   <p>
      <span class="anchor_label">(9) </span>
      <span class="page">[181v] </span>
         even so <span class="page">[182r] </span> are you among us, glorious Devgenij.
      </p>
</div>
<div id="m10">
   <p>
      <span class="anchor_label">(10) </span>
      <span class="page">[182r] </span>
         And we, glorious Devgenij, entreat you: play not the sluggard, bestir yourself;
      </p>
</div>
<div id="m11">
   <p>
      <span class="anchor_label">(11) </span>
      <span class="page">[182r] </span>
         come to us with no large force to the river Euphrates,
      </p>
</div>
<div id="m12">
   <p>
      <span class="anchor_label">(12) </span>
      <span class="page">[182r] </span>
         that we may see your youthfulness and bravery; there is no plot against you at all.
      </p>
</div>
<div id="m13">
   <p>
      <span class="anchor_label">(13) </span>
      <span class="page">[182r] </span>And glorious Devgenij read the missive</p>
</div>
<div id="m14">
   <p>
      <span class="anchor_label">(14) </span>
      <span class="page">[182r] </span>and laughed</p>
</div>
<div id="m15">
   <p>
      <span class="anchor_label">(15) </span>
      <span class="page">[182r] </span>and said to his father: Father, I wish to go and see glorious and brave
            Filipap and the maiden Maksimijana,
      </p>
</div>
<div id="m16">
   <p>
      <span class="anchor_label">(16) </span>
      <span class="page">[182r] </span>But his father said: My dear child, glorious Devgenij, it is too early
            for you to think of battle;
      </p>
</div>
<div id="m17">
   <p>
      <span class="anchor_label">(17) </span>
      <span class="page">[182r] </span>
         you have not been in victorious battles, whereas Filipap in battles is strong and brave
            and the maiden Maksimijana is also, and he has a great force.
      </p>
</div>
<div id="m18">
   <p>
      <span class="anchor_label">(18) </span>
      <span class="page">[182r] </span>But Devgenij replied to the missive; he sent his favorite to them and
         said:</p>
</div>
<div id="m19">
   <p>
      <span class="anchor_label">(19) </span>
      <span class="page">[182r] </span>
         It is a great shame for me to go to fight against a woman,
      </p>
</div>
<div id="m20">
   <p>
      <span class="anchor_label">(20) </span>
      <span class="page">[182r] </span>
         but you, Filipap, old uncle, why have you come in great strength and led a host of
            innocent people against me?
      </p>
</div>
<div id="m21">
   <p>
      <span class="anchor_label">(21) </span>
      <span class="page">[182r] </span>The maiden Maksimijana said: Do not, brilliant sun, glorious Devgenij,
            have any such thought in your mind at all, since we have come see your youthfulness.
      </p>
</div>
<div id="m22">
   <p>
      <span class="anchor_label">(22) </span>
      <span class="page">[182r] </span>Day after day Devgenij was thinking how he might see the bravery
            <span class="page">[182v] </span> of Filipap.</p>
</div>
<div id="m23">
   <p>
      <span class="anchor_label">(23) </span>
      <span class="page">[182v] </span>
         And he took a few of his favorites with him and asked a prayer from
         his father and from his mother: Quickly bless me, father and mother mine.
      </p>
</div>
<div id="m24">
   <p>
      <span class="anchor_label">(24) </span>
      <span class="page">[182v] </span>
         Have no concern at all over this; no wounds will be on my body from the hand of man,
      </p>
</div>
<div id="m25">
   <p>
      <span class="anchor_label">(25) </span>
      <span class="page">[182v] </span>
         since I put my trust in the strength of God and in your fatherly grace and that of my
            mother.
      </p>
</div>
<div id="m26">
   <p>
      <span class="anchor_label">(26) </span>
      <span class="page">[182v] </span>And mounting his horse he went on his way.</p>
</div>
<div id="m27">
   <p>
      <span class="anchor_label">(27) </span>
      <span class="page">[182v] </span>He reached the river Euphrates and stood on the bank</p>
</div>
<div id="m28">
   <p>
      <span class="anchor_label">(28) </span>
      <span class="page">[182v] </span>and sent his favorites to Filipap and the maiden Maksimijana.</p>
</div>
<div id="m29">
   <p>
      <span class="anchor_label">(29) </span>
      <span class="page">[182v] </span>When Filipap saw that Devgenij had few soldiers,</p>
</div>
<div id="m30">
   <p>
      <span class="anchor_label">(30) </span>
      <span class="page">[182v] </span>he began to chase them with his whole army.</p>
</div>
<div id="m31">
   <p>
      <span class="anchor_label">(31) </span>
      <span class="page">[182v] </span>When Devgenij saw his followers pursued,</p>
</div>
<div id="m32">
   <p>
      <span class="anchor_label">(32) </span>
      <span class="page">[182v] </span>grasping his lance he planted his lance in the river and vaulted over on
         foot like a fierce falcon from a hunter's hand;</p>
</div>
<div id="m33">
   <p>
      <span class="anchor_label">(33) </span>
      <span class="page">[182v] </span>he cried in a loud voice: Give me my horse called Far'!
      </p>
</div>
<div id="m34">
   <p>
      <span class="anchor_label">(34) </span>
      <span class="page">[182v] </span>And mounting his horse he began to chase them as a good mower to mow grass:
         in the first mowing a thousand, in the second another thousand he conquered;</p>
</div>
<div id="m35">
   <p>
      <span class="anchor_label">(35) </span>
      <span class="page">[182v] </span>in the third mowing he overtook Filipap and smote him between the shoulders
         with his mace and knocked him off his horse.</p>
</div>
<div id="m36">
   <p>
      <span class="anchor_label">(36) </span>
      <span class="page">[182v] </span>
         When the maiden Maksimijana saw that Devgenij was binding Filipap,</p>
</div>
<div id="m37">
   <p>
      <span class="anchor_label">(37) </span>
      <span class="page">[182v] </span>she aimed her lance, wishing to run glorious Devgenij through
            <span class="page">[183r] </span> from behind.</p>
</div>
<div id="m38">
   <p>
      <span class="anchor_label">(38) </span>
      <span class="page">[183r] </span>Seeing this, Devgenij grasped her lance and smote her with his lance and
         knocked her off her horse.</p>
</div>
<div id="m39">
   <p>
      <span class="anchor_label">(39) </span>
      <span class="page">[183r] </span>And having taken Filipap and the maiden Maksimijana,</p>
</div>
<div id="m40">
   <p>
      <span class="anchor_label">(40) </span>
      <span class="page">[183r] </span>some he killed, while some he bound, and he drove them before him as a good
         shepherd drove sheep through a river.</p>
</div>
<div id="m41">
   <p>
      <span class="anchor_label">(41) </span>
      <span class="page">[183r] </span>At that time old uncle Filipap turned to Devgenij and said:</p>
</div>
<div id="m42">
   <p>
      <span class="anchor_label">(42) </span>
      <span class="page">[183r] </span>
         Gold-winged hawk, glorious Devgenij, you are glorious among us all, the strong and the
            brave. But there is yet a braver and a stronger one than you in the world,
      </p>
</div>
<div id="m43">
   <p>
      <span class="anchor_label">(43) </span>
      <span class="page">[183r] </span>
         glorious Stratig, who has four sons; the rest of his army the earth cannot contain.
      </p>
</div>
<div id="m44">
   <p>
      <span class="anchor_label">(44) </span>
      <span class="page">[183r] </span>
         And he has a daughter, the very glorious and beautiful Stratigovna;
            she has manly boldness and bravery,
      </p>
</div>
<div id="m45">
   <p>
      <span class="anchor_label">(45) </span>
      <span class="page">[183r] </span>
         while there is nothing fairer on earth than her fairness.
      </p>
</div>
<div id="m46">
   <p>
      <span class="anchor_label">(46) </span>
      <span class="page">[183r] </span>
         Many tsars and kings, brave and strong, have come, but no one can take her,
      </p>
</div>
<div id="m47">
   <p>
      <span class="anchor_label">(47) </span>
      <span class="page">[183r] </span>
         and to no one is she like in beauty and strength.
      </p>
</div>
<div id="m48">
   <p>
      <span class="anchor_label">(48) </span>
      <span class="page">[183r] </span>
         But now spare my years; after a little let me go. Glorious Devgenij said: I wish
            to learn whether you are speaking the truth; then I shall let you go; I shall put my
            mark on your face for all time.
      </p>
</div>
<div id="m49">
   <p>
      <span class="anchor_label">(49) </span>
      <span class="page">[183r] </span>The maiden Maksimijana also began to entreat him: O light, brilliant sun,
            glorious Devgenij, <span class="page">[183v] </span> to me have come many tsars and kings, brave and
            strong in much strength, but no one has dishonored me with a single word;
      </p>
</div>
<div id="m50">
   <p>
      <span class="anchor_label">(50) </span>
      <span class="page">[183v] </span>
         all have been conquered by my hands.
      </p>
</div>
<div id="m51">
   <p>
      <span class="anchor_label">(51) </span>
      <span class="page">[183v] </span>
         But now God has submitted me to you.
      </p>
</div>
<div id="m52">
   <p>
      <span class="anchor_label">(52) </span>
      <span class="page">[183v] </span>
         If you join with me, there will be nothing stronger than we and no one can stand
               against us.
      </p>
</div>
<div id="m53">
   <p>
      <span class="anchor_label">(53) </span>
      <span class="page">[183v] </span>Glorious Devgenij said: Brother, Maksimijana, I have no man's help save
            the grace of God and my mother's prayer: that will help me.
      </p>
</div>
<div id="m54">
   <p>
      <span class="anchor_label">(54) </span>
      <span class="page">[183v] </span>For Devgenij it is written: If you join with Maksimijana, his life is
            sixteen years; if he joins with Stratigovna, his life is thirty-six years.
      </p>
</div>
<div id="m55">
   <p>
      <span class="anchor_label">(55) </span>
      <span class="page">[183v] </span>
         Devgenij called loudly for his favorite and said: Go to my father
            and my mother and say to them thus:
      </p>
</div>
<div id="m56">
   <p>
      <span class="anchor_label">(56) </span>
      <span class="page">[183v] </span>
         Rejoice, father and mother mine, that I have defeated Filipap.
      </p>
</div>
<div id="m57">
   <p>
      <span class="anchor_label">(57) </span>
      <span class="page">[183v] </span>
         And take him to my father and Maksimijana here to my mother. If you
            offend her with even a single word, this day you cease to live.
      </p>
</div>
<div id="m58">
   <p>
      <span class="anchor_label">(58) </span>
      <span class="page">[183v] </span>The favorite came to his Devgenij's father's and
         mother's house and brought them Filipap and the maiden Maksimijana and told them all in
         order.</p>
</div>
<div id="m59">
   <p>
      <span class="anchor_label">(59) </span>
      <span class="page">[183v] </span>His father and mother were ever very joyful about him.</p>
</div>
<div id="my">
   <p>
      <span class="anchor_label">(y) </span>
      <span class="page">[19r] </span>[Emperor (Slavic)] And he placed brands on the faces of Kanam and Ioakim and
         sent them to their native country.</p>
</div>
<div id="mz">
   <p>
      <span class="anchor_label">(z) </span>
      <span class="page">[16r] </span>[Abduction (Slavic)] And he branded uncle Filipap on the face and then sent
         him off to where he had come from, and Maksimijana’s liberation he announced through his
         servants.</p>
</div>
